repo:
  - all: [ '*', '!CMakeLists.txt', '!CMakePresets.json' ]

documentation:
  - any: [ 'README.md', 'docs/**' ]

tests:
  - tests/**

game:
  - game/**

sponge:
  - sponge/**

cmake:
  - any: [ '**/CMakeLists.txt', 'CMakePresets.json', 'cmake/**' ]

ci:
  - .github/workflows/**
