#pragma once

// for use by Sponge applications

#include "core/base.h"
#include "core/engine.h"
#include "core/file.h"
#include "core/input.h"
#include "core/keycode.h"
#include "core/log.h"
#include "core/logflag.h"
#include "core/mousecode.h"
#include "core/timer.h"
#include "core/window.h"
#include "event/applicationevent.h"
#include "event/event.h"
#include "event/keyevent.h"
#include "event/mouseevent.h"
#include "imgui/imguimanager.h"
#include "imgui/imguinullmanager.h"
#include "imgui/imguisink.h"
#include "layer/layer.h"
#include "layer/layerstack.h"
#include "platform/opengl/openglquad.h"
#include "platform/opengl/openglresourcemanager.h"
#include "platform/opengl/openglsprite.h"
#include "platform/sdl/sdlengine.h"
#include "platform/sdl/sdlinput.h"
#include "renderer/buffer.h"
#include "renderer/camera.h"
#include "renderer/graphicscontext.h"
#include "renderer/mesh.h"
#include "renderer/orthocamera.h"
#include "renderer/rendererapi.h"
#include "renderer/shader.h"
#include "renderer/sprite.h"
#include "renderer/texture.h"
#include "renderer/vertexarray.h"
