#pragma once

// for use by Sponge applications

#include "core/base.h"
#include "core/engine.h"
#include "core/input.h"
#include "core/keycode.h"
#include "core/layer.h"
#include "core/layerstack.h"
#include "core/log.h"
#include "core/mousecode.h"
#include "event/applicationevent.h"
#include "event/event.h"
#include "event/keyevent.h"
#include "event/mouseevent.h"
#include "platform/sdl/sdlengine.h"
#include "platform/sdl/sdlinput.h"
#include "renderer/buffer.h"
#include "renderer/graphicscontext.h"
#include "renderer/mesh.h"
#include "renderer/opengl/openglresourcemanager.h"
#include "renderer/opengl/openglsprite.h"
#include "renderer/rendererapi.h"
#include "renderer/shader.h"
#include "renderer/sprite.h"
#include "renderer/texture.h"
#include "renderer/vertexarray.h"
#include "scene/camera.h"
#include "scene/orthocamera.h"
