#pragma once

// for use by Sponge applications

#include "core/application.hpp"
#include "core/base.hpp"
#include "core/color.hpp"
#include "core/file.hpp"
#include "core/timer.hpp"
#include "core/window.hpp"
#include "debug/profiler.hpp"
#include "event/applicationevent.hpp"
#include "event/event.hpp"
#include "event/keyevent.hpp"
#include "event/mouseevent.hpp"
#include "input/keycode.hpp"
#include "input/mousecode.hpp"
#include "layer/layer.hpp"
#include "layer/layerstack.hpp"
#include "logging/log.hpp"
#include "logging/logcustom.hpp"
#include "logging/logflag.hpp"
#include "platform/glfw/core/application.hpp"
#include "platform/glfw/core/input.hpp"
#include "platform/glfw/core/window.hpp"
#include "platform/glfw/logging/sink.hpp"
#include "platform/opengl/debug/diagnostics.hpp"
#include "platform/opengl/debug/profiler.hpp"
#include "platform/opengl/renderer/buffer.hpp"
#include "platform/opengl/renderer/context.hpp"
#include "platform/opengl/renderer/errorhandler.hpp"
#include "platform/opengl/renderer/framebuffer.hpp"
#include "platform/opengl/renderer/indexbuffer.hpp"
#include "platform/opengl/renderer/rendererapi.hpp"
#include "platform/opengl/renderer/resourcemanager.hpp"
#include "platform/opengl/renderer/shader.hpp"
#include "platform/opengl/renderer/texture.hpp"
#include "platform/opengl/renderer/vertexarray.hpp"
#include "platform/opengl/renderer/vertexbuffer.hpp"
#include "platform/opengl/scene/cube.hpp"
#include "platform/opengl/scene/font.hpp"
#include "platform/opengl/scene/mesh.hpp"
#include "platform/opengl/scene/model.hpp"
#include "platform/opengl/scene/quad.hpp"
#include "platform/opengl/scene/shadowmap.hpp"
#include "platform/opengl/scene/sprite.hpp"
#include "scene/font.hpp"
#include "scene/mesh.hpp"
#include "scene/sprite.hpp"

#if defined(ENABLE_IMGUI)
#include "platform/glfw/imgui/glfwmanager.hpp"
#include "platform/glfw/imgui/imguimanager.hpp"
#include "platform/glfw/imgui/noopmanager.hpp"
#endif
