#pragma once

// for use by Sponge applications

#include "core/base.hpp"
#include "core/engine.hpp"
#include "core/file.hpp"
#include "core/input.hpp"
#include "core/keycode.hpp"
#include "core/log.hpp"
#include "core/logflag.hpp"
#include "core/mousecode.hpp"
#include "core/timer.hpp"
#include "core/window.hpp"
#include "event/applicationevent.hpp"
#include "event/event.hpp"
#include "event/keyevent.hpp"
#include "event/mouseevent.hpp"
#include "imgui/imguimanager.hpp"
#include "imgui/imguinullmanager.hpp"
#include "imgui/imguisink.hpp"
#include "layer/layer.hpp"
#include "layer/layerstack.hpp"
#include "platform/opengl/openglquad.hpp"
#include "platform/opengl/openglresourcemanager.hpp"
#include "platform/opengl/openglsprite.hpp"
#include "platform/sdl/sdlengine.hpp"
#include "platform/sdl/sdlinput.hpp"
#include "renderer/buffer.hpp"
#include "renderer/camera.hpp"
#include "renderer/graphicscontext.hpp"
#include "renderer/mesh.hpp"
#include "renderer/orthocamera.hpp"
#include "renderer/rendererapi.hpp"
#include "renderer/shader.hpp"
#include "renderer/sprite.hpp"
#include "renderer/texture.hpp"
#include "renderer/vertexarray.hpp"
