#pragma once

// for use by Sponge applications

#include "core/base.h"
#include "core/engine.h"
#include "core/file.h"
#include "core/input.h"
#include "core/keycode.h"
#include "core/log.h"
#include "core/mousecode.h"
#include "event/applicationevent.h"
#include "event/event.h"
#include "event/keyevent.h"
#include "event/mouseevent.h"
#include "graphics/camera/camera.h"
#include "graphics/camera/orthocamera.h"
#include "graphics/renderer/buffer.h"
#include "graphics/renderer/graphicscontext.h"
#include "graphics/renderer/mesh.h"
#include "graphics/renderer/rendererapi.h"
#include "graphics/renderer/shader.h"
#include "graphics/renderer/sprite.h"
#include "graphics/renderer/texture.h"
#include "graphics/renderer/vertexarray.h"
#include "imgui/imguilayer.h"
#include "layer/layer.h"
#include "layer/layerstack.h"
#include "platform/opengl/openglquad.h"
#include "platform/opengl/openglresourcemanager.h"
#include "platform/opengl/openglsprite.h"
#include "platform/sdl/sdlengine.h"
#include "platform/sdl/sdlinput.h"
