#pragma once

#include "input/keycode.hpp"
#include <SDL.h>
#include <unordered_map>

namespace sponge::platform::sdl::input {

using input::KeyCode;

// map SDL scan codes to engine key codes
static std::unordered_map<SDL_Scancode, KeyCode> keyCodeMap = {
    { SDL_SCANCODE_SPACE, KeyCode::SpongeKey_Space },
    { SDL_SCANCODE_APOSTROPHE, KeyCode::SpongeKey_Apostrophe },
    { SDL_SCANCODE_COMMA, KeyCode::SpongeKey_Comma },
    { SDL_SCANCODE_MINUS, KeyCode::SpongeKey_Minus },
    { SDL_SCANCODE_PERIOD, KeyCode::SpongeKey_Period },
    { SDL_SCANCODE_SLASH, KeyCode::SpongeKey_Slash },

    { SDL_SCANCODE_0, KeyCode::SpongeKey_D0 },
    { SDL_SCANCODE_1, KeyCode::SpongeKey_D1 },
    { SDL_SCANCODE_2, KeyCode::SpongeKey_D2 },
    { SDL_SCANCODE_3, KeyCode::SpongeKey_D3 },
    { SDL_SCANCODE_4, KeyCode::SpongeKey_D4 },
    { SDL_SCANCODE_5, KeyCode::SpongeKey_D5 },
    { SDL_SCANCODE_6, KeyCode::SpongeKey_D6 },
    { SDL_SCANCODE_7, KeyCode::SpongeKey_D7 },
    { SDL_SCANCODE_8, KeyCode::SpongeKey_D8 },
    { SDL_SCANCODE_9, KeyCode::SpongeKey_D9 },

    { SDL_SCANCODE_SEMICOLON, KeyCode::SpongeKey_Semicolon },
    { SDL_SCANCODE_EQUALS, KeyCode::SpongeKey_Equal },

    { SDL_SCANCODE_A, KeyCode::SpongeKey_A },
    { SDL_SCANCODE_B, KeyCode::SpongeKey_B },
    { SDL_SCANCODE_C, KeyCode::SpongeKey_C },
    { SDL_SCANCODE_D, KeyCode::SpongeKey_D },
    { SDL_SCANCODE_E, KeyCode::SpongeKey_E },
    { SDL_SCANCODE_F, KeyCode::SpongeKey_F },
    { SDL_SCANCODE_G, KeyCode::SpongeKey_G },
    { SDL_SCANCODE_H, KeyCode::SpongeKey_H },
    { SDL_SCANCODE_I, KeyCode::SpongeKey_I },
    { SDL_SCANCODE_J, KeyCode::SpongeKey_J },
    { SDL_SCANCODE_K, KeyCode::SpongeKey_K },
    { SDL_SCANCODE_L, KeyCode::SpongeKey_L },
    { SDL_SCANCODE_M, KeyCode::SpongeKey_M },
    { SDL_SCANCODE_N, KeyCode::SpongeKey_N },
    { SDL_SCANCODE_O, KeyCode::SpongeKey_O },
    { SDL_SCANCODE_P, KeyCode::SpongeKey_P },
    { SDL_SCANCODE_Q, KeyCode::SpongeKey_Q },
    { SDL_SCANCODE_R, KeyCode::SpongeKey_R },
    { SDL_SCANCODE_S, KeyCode::SpongeKey_S },
    { SDL_SCANCODE_T, KeyCode::SpongeKey_T },
    { SDL_SCANCODE_U, KeyCode::SpongeKey_U },
    { SDL_SCANCODE_V, KeyCode::SpongeKey_V },
    { SDL_SCANCODE_W, KeyCode::SpongeKey_W },
    { SDL_SCANCODE_X, KeyCode::SpongeKey_X },
    { SDL_SCANCODE_Y, KeyCode::SpongeKey_Y },
    { SDL_SCANCODE_Z, KeyCode::SpongeKey_Z },

    { SDL_SCANCODE_LEFTBRACKET, KeyCode::SpongeKey_LeftBracket },
    { SDL_SCANCODE_BACKSLASH, KeyCode::SpongeKey_Backslash },
    { SDL_SCANCODE_RIGHTBRACKET, KeyCode::SpongeKey_RightBracket },
    { SDL_SCANCODE_GRAVE, KeyCode::SpongeKey_GraveAccent },

    { SDL_SCANCODE_INTERNATIONAL1, KeyCode::SpongeKey_World1 },
    { SDL_SCANCODE_INTERNATIONAL2, KeyCode::SpongeKey_World2 },

    { SDL_SCANCODE_ESCAPE, KeyCode::SpongeKey_Escape },
    { SDL_SCANCODE_RETURN, KeyCode::SpongeKey_Enter },
    { SDL_SCANCODE_TAB, KeyCode::SpongeKey_Tab },
    { SDL_SCANCODE_BACKSPACE, KeyCode::SpongeKey_Backspace },
    { SDL_SCANCODE_INSERT, KeyCode::SpongeKey_Insert },
    { SDL_SCANCODE_DELETE, KeyCode::SpongeKey_Delete },
    { SDL_SCANCODE_RIGHT, KeyCode::SpongeKey_Right },
    { SDL_SCANCODE_LEFT, KeyCode::SpongeKey_Left },
    { SDL_SCANCODE_DOWN, KeyCode::SpongeKey_Down },
    { SDL_SCANCODE_UP, KeyCode::SpongeKey_Up },
    { SDL_SCANCODE_PAGEUP, KeyCode::SpongeKey_PageUp },
    { SDL_SCANCODE_PAGEDOWN, KeyCode::SpongeKey_PageDown },
    { SDL_SCANCODE_HOME, KeyCode::SpongeKey_Home },
    { SDL_SCANCODE_END, KeyCode::SpongeKey_End },
    { SDL_SCANCODE_CAPSLOCK, KeyCode::SpongeKey_CapsLock },
    { SDL_SCANCODE_SCROLLLOCK, KeyCode::SpongeKey_ScrollLock },
    { SDL_SCANCODE_NUMLOCKCLEAR, KeyCode::SpongeKey_NumLock },
    { SDL_SCANCODE_PRINTSCREEN, KeyCode::SpongeKey_PrintScreen },
    { SDL_SCANCODE_PAUSE, KeyCode::SpongeKey_Pause },
    { SDL_SCANCODE_F1, KeyCode::SpongeKey_F1 },
    { SDL_SCANCODE_F2, KeyCode::SpongeKey_F2 },
    { SDL_SCANCODE_F3, KeyCode::SpongeKey_F3 },
    { SDL_SCANCODE_F4, KeyCode::SpongeKey_F4 },
    { SDL_SCANCODE_F5, KeyCode::SpongeKey_F5 },
    { SDL_SCANCODE_F6, KeyCode::SpongeKey_F6 },
    { SDL_SCANCODE_F7, KeyCode::SpongeKey_F7 },
    { SDL_SCANCODE_F8, KeyCode::SpongeKey_F8 },
    { SDL_SCANCODE_F9, KeyCode::SpongeKey_F9 },
    { SDL_SCANCODE_F10, KeyCode::SpongeKey_F10 },
    { SDL_SCANCODE_F11, KeyCode::SpongeKey_F11 },
    { SDL_SCANCODE_F12, KeyCode::SpongeKey_F12 },
    { SDL_SCANCODE_F13, KeyCode::SpongeKey_F13 },
    { SDL_SCANCODE_F14, KeyCode::SpongeKey_F14 },
    { SDL_SCANCODE_F15, KeyCode::SpongeKey_F15 },
    { SDL_SCANCODE_F16, KeyCode::SpongeKey_F16 },
    { SDL_SCANCODE_F17, KeyCode::SpongeKey_F17 },
    { SDL_SCANCODE_F18, KeyCode::SpongeKey_F18 },
    { SDL_SCANCODE_F19, KeyCode::SpongeKey_F19 },
    { SDL_SCANCODE_F20, KeyCode::SpongeKey_F20 },
    { SDL_SCANCODE_F21, KeyCode::SpongeKey_F21 },
    { SDL_SCANCODE_F22, KeyCode::SpongeKey_F22 },
    { SDL_SCANCODE_F23, KeyCode::SpongeKey_F23 },
    { SDL_SCANCODE_F24, KeyCode::SpongeKey_F24 },

    { SDL_SCANCODE_KP_0, KeyCode::SpongeKey_KP0 },
    { SDL_SCANCODE_KP_1, KeyCode::SpongeKey_KP1 },
    { SDL_SCANCODE_KP_2, KeyCode::SpongeKey_KP2 },
    { SDL_SCANCODE_KP_3, KeyCode::SpongeKey_KP3 },
    { SDL_SCANCODE_KP_4, KeyCode::SpongeKey_KP4 },
    { SDL_SCANCODE_KP_5, KeyCode::SpongeKey_KP5 },
    { SDL_SCANCODE_KP_6, KeyCode::SpongeKey_KP6 },
    { SDL_SCANCODE_KP_7, KeyCode::SpongeKey_KP7 },
    { SDL_SCANCODE_KP_8, KeyCode::SpongeKey_KP8 },
    { SDL_SCANCODE_KP_9, KeyCode::SpongeKey_KP9 },
    { SDL_SCANCODE_KP_DECIMAL, KeyCode::SpongeKey_KPDecimal },
    { SDL_SCANCODE_KP_DIVIDE, KeyCode::SpongeKey_KPDivide },
    { SDL_SCANCODE_KP_MULTIPLY, KeyCode::SpongeKey_KPMultiply },
    { SDL_SCANCODE_KP_MINUS, KeyCode::SpongeKey_KPSubtract },
    { SDL_SCANCODE_KP_PLUS, KeyCode::SpongeKey_KPAdd },
    { SDL_SCANCODE_KP_ENTER, KeyCode::SpongeKey_KPEnter },
    { SDL_SCANCODE_KP_EQUALS, KeyCode::SpongeKey_KPEqual },

    { SDL_SCANCODE_LSHIFT, KeyCode::SpongeKey_LeftShift },
    { SDL_SCANCODE_LCTRL, KeyCode::SpongeKey_LeftControl },
    { SDL_SCANCODE_LALT, KeyCode::SpongeKey_LeftAlt },
    { SDL_SCANCODE_LGUI, KeyCode::SpongeKey_LeftSuper },
    { SDL_SCANCODE_RSHIFT, KeyCode::SpongeKey_RightShift },
    { SDL_SCANCODE_RCTRL, KeyCode::SpongeKey_RightControl },
    { SDL_SCANCODE_RALT, KeyCode::SpongeKey_RightAlt },
    { SDL_SCANCODE_RGUI, KeyCode::SpongeKey_RightSuper },
    { SDL_SCANCODE_MENU, KeyCode::SpongeKey_Menu }
};

// map engine key codes to SDL scan codes
static std::unordered_map<KeyCode, SDL_Scancode> scanCodeMap = {
    { KeyCode::SpongeKey_Space, SDL_SCANCODE_SPACE },
    { KeyCode::SpongeKey_Apostrophe, SDL_SCANCODE_APOSTROPHE },
    { KeyCode::SpongeKey_Comma, SDL_SCANCODE_COMMA },
    { KeyCode::SpongeKey_Minus, SDL_SCANCODE_MINUS },
    { KeyCode::SpongeKey_Period, SDL_SCANCODE_PERIOD },
    { KeyCode::SpongeKey_Slash, SDL_SCANCODE_SLASH },

    { KeyCode::SpongeKey_D0, SDL_SCANCODE_0 },
    { KeyCode::SpongeKey_D1, SDL_SCANCODE_1 },
    { KeyCode::SpongeKey_D2, SDL_SCANCODE_2 },
    { KeyCode::SpongeKey_D3, SDL_SCANCODE_3 },
    { KeyCode::SpongeKey_D4, SDL_SCANCODE_4 },
    { KeyCode::SpongeKey_D5, SDL_SCANCODE_5 },
    { KeyCode::SpongeKey_D6, SDL_SCANCODE_6 },
    { KeyCode::SpongeKey_D7, SDL_SCANCODE_7 },
    { KeyCode::SpongeKey_D8, SDL_SCANCODE_8 },
    { KeyCode::SpongeKey_D9, SDL_SCANCODE_9 },

    { KeyCode::SpongeKey_Semicolon, SDL_SCANCODE_SEMICOLON },
    { KeyCode::SpongeKey_Equal, SDL_SCANCODE_EQUALS },

    { KeyCode::SpongeKey_A, SDL_SCANCODE_A },
    { KeyCode::SpongeKey_B, SDL_SCANCODE_B },
    { KeyCode::SpongeKey_C, SDL_SCANCODE_C },
    { KeyCode::SpongeKey_D, SDL_SCANCODE_D },
    { KeyCode::SpongeKey_E, SDL_SCANCODE_E },
    { KeyCode::SpongeKey_F, SDL_SCANCODE_F },
    { KeyCode::SpongeKey_G, SDL_SCANCODE_G },
    { KeyCode::SpongeKey_H, SDL_SCANCODE_H },
    { KeyCode::SpongeKey_I, SDL_SCANCODE_I },
    { KeyCode::SpongeKey_J, SDL_SCANCODE_J },
    { KeyCode::SpongeKey_K, SDL_SCANCODE_K },
    { KeyCode::SpongeKey_L, SDL_SCANCODE_L },
    { KeyCode::SpongeKey_M, SDL_SCANCODE_M },
    { KeyCode::SpongeKey_N, SDL_SCANCODE_N },
    { KeyCode::SpongeKey_O, SDL_SCANCODE_O },
    { KeyCode::SpongeKey_P, SDL_SCANCODE_P },
    { KeyCode::SpongeKey_Q, SDL_SCANCODE_Q },
    { KeyCode::SpongeKey_R, SDL_SCANCODE_R },
    { KeyCode::SpongeKey_S, SDL_SCANCODE_S },
    { KeyCode::SpongeKey_T, SDL_SCANCODE_T },
    { KeyCode::SpongeKey_U, SDL_SCANCODE_U },
    { KeyCode::SpongeKey_V, SDL_SCANCODE_V },
    { KeyCode::SpongeKey_W, SDL_SCANCODE_W },
    { KeyCode::SpongeKey_X, SDL_SCANCODE_X },
    { KeyCode::SpongeKey_Y, SDL_SCANCODE_Y },
    { KeyCode::SpongeKey_Z, SDL_SCANCODE_Z },

    { KeyCode::SpongeKey_LeftBracket, SDL_SCANCODE_LEFTBRACKET },
    { KeyCode::SpongeKey_Backslash, SDL_SCANCODE_BACKSLASH },
    { KeyCode::SpongeKey_RightBracket, SDL_SCANCODE_RIGHTBRACKET },
    { KeyCode::SpongeKey_GraveAccent, SDL_SCANCODE_GRAVE },

    { KeyCode::SpongeKey_World1, SDL_SCANCODE_INTERNATIONAL1 },
    { KeyCode::SpongeKey_World2, SDL_SCANCODE_INTERNATIONAL2 },

    { KeyCode::SpongeKey_Escape, SDL_SCANCODE_ESCAPE },
    { KeyCode::SpongeKey_Enter, SDL_SCANCODE_RETURN },
    { KeyCode::SpongeKey_Tab, SDL_SCANCODE_TAB },
    { KeyCode::SpongeKey_Backspace, SDL_SCANCODE_BACKSPACE },
    { KeyCode::SpongeKey_Insert, SDL_SCANCODE_INSERT },
    { KeyCode::SpongeKey_Delete, SDL_SCANCODE_DELETE },
    { KeyCode::SpongeKey_Right, SDL_SCANCODE_RIGHT },
    { KeyCode::SpongeKey_Left, SDL_SCANCODE_LEFT },
    { KeyCode::SpongeKey_Down, SDL_SCANCODE_DOWN },
    { KeyCode::SpongeKey_Up, SDL_SCANCODE_UP },
    { KeyCode::SpongeKey_PageUp, SDL_SCANCODE_PAGEUP },
    { KeyCode::SpongeKey_PageDown, SDL_SCANCODE_PAGEDOWN },
    { KeyCode::SpongeKey_Home, SDL_SCANCODE_HOME },
    { KeyCode::SpongeKey_End, SDL_SCANCODE_END },
    { KeyCode::SpongeKey_CapsLock, SDL_SCANCODE_CAPSLOCK },
    { KeyCode::SpongeKey_ScrollLock, SDL_SCANCODE_SCROLLLOCK },
    { KeyCode::SpongeKey_NumLock, SDL_SCANCODE_NUMLOCKCLEAR },
    { KeyCode::SpongeKey_PrintScreen, SDL_SCANCODE_PRINTSCREEN },
    { KeyCode::SpongeKey_Pause, SDL_SCANCODE_PAUSE },
    { KeyCode::SpongeKey_F1, SDL_SCANCODE_F1 },
    { KeyCode::SpongeKey_F2, SDL_SCANCODE_F2 },
    { KeyCode::SpongeKey_F3, SDL_SCANCODE_F3 },
    { KeyCode::SpongeKey_F4, SDL_SCANCODE_F4 },
    { KeyCode::SpongeKey_F5, SDL_SCANCODE_F5 },
    { KeyCode::SpongeKey_F6, SDL_SCANCODE_F6 },
    { KeyCode::SpongeKey_F7, SDL_SCANCODE_F7 },
    { KeyCode::SpongeKey_F8, SDL_SCANCODE_F8 },
    { KeyCode::SpongeKey_F9, SDL_SCANCODE_F9 },
    { KeyCode::SpongeKey_F10, SDL_SCANCODE_F10 },
    { KeyCode::SpongeKey_F11, SDL_SCANCODE_F11 },
    { KeyCode::SpongeKey_F12, SDL_SCANCODE_F12 },
    { KeyCode::SpongeKey_F13, SDL_SCANCODE_F13 },
    { KeyCode::SpongeKey_F14, SDL_SCANCODE_F14 },
    { KeyCode::SpongeKey_F15, SDL_SCANCODE_F15 },
    { KeyCode::SpongeKey_F16, SDL_SCANCODE_F16 },
    { KeyCode::SpongeKey_F17, SDL_SCANCODE_F17 },
    { KeyCode::SpongeKey_F18, SDL_SCANCODE_F18 },
    { KeyCode::SpongeKey_F19, SDL_SCANCODE_F19 },
    { KeyCode::SpongeKey_F20, SDL_SCANCODE_F20 },
    { KeyCode::SpongeKey_F21, SDL_SCANCODE_F21 },
    { KeyCode::SpongeKey_F22, SDL_SCANCODE_F22 },
    { KeyCode::SpongeKey_F23, SDL_SCANCODE_F23 },
    { KeyCode::SpongeKey_F24, SDL_SCANCODE_F24 },

    { KeyCode::SpongeKey_KP0, SDL_SCANCODE_KP_0 },
    { KeyCode::SpongeKey_KP1, SDL_SCANCODE_KP_1 },
    { KeyCode::SpongeKey_KP2, SDL_SCANCODE_KP_2 },
    { KeyCode::SpongeKey_KP3, SDL_SCANCODE_KP_3 },
    { KeyCode::SpongeKey_KP4, SDL_SCANCODE_KP_4 },
    { KeyCode::SpongeKey_KP5, SDL_SCANCODE_KP_5 },
    { KeyCode::SpongeKey_KP6, SDL_SCANCODE_KP_6 },
    { KeyCode::SpongeKey_KP7, SDL_SCANCODE_KP_7 },
    { KeyCode::SpongeKey_KP8, SDL_SCANCODE_KP_8 },
    { KeyCode::SpongeKey_KP9, SDL_SCANCODE_KP_9 },
    { KeyCode::SpongeKey_KPDecimal, SDL_SCANCODE_KP_DECIMAL },
    { KeyCode::SpongeKey_KPDivide, SDL_SCANCODE_KP_DIVIDE },
    { KeyCode::SpongeKey_KPMultiply, SDL_SCANCODE_KP_MULTIPLY },
    { KeyCode::SpongeKey_KPSubtract, SDL_SCANCODE_KP_MINUS },
    { KeyCode::SpongeKey_KPAdd, SDL_SCANCODE_KP_PLUS },
    { KeyCode::SpongeKey_KPEnter, SDL_SCANCODE_KP_ENTER },
    { KeyCode::SpongeKey_KPEqual, SDL_SCANCODE_KP_EQUALS },

    { KeyCode::SpongeKey_LeftShift, SDL_SCANCODE_LSHIFT },
    { KeyCode::SpongeKey_LeftControl, SDL_SCANCODE_LCTRL },
    { KeyCode::SpongeKey_LeftAlt, SDL_SCANCODE_LALT },
    { KeyCode::SpongeKey_LeftSuper, SDL_SCANCODE_LGUI },
    { KeyCode::SpongeKey_RightShift, SDL_SCANCODE_RSHIFT },
    { KeyCode::SpongeKey_RightControl, SDL_SCANCODE_RCTRL },
    { KeyCode::SpongeKey_RightAlt, SDL_SCANCODE_RALT },
    { KeyCode::SpongeKey_RightSuper, SDL_SCANCODE_RGUI },
    { KeyCode::SpongeKey_Menu, SDL_SCANCODE_MENU }
};

}  // namespace sponge::platform::sdl::input
