name: build

on:
    push:
        branches: [main, feature/*]
    pull_request:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ci-${{github.event.pull_request.number || github.ref}}
    cancel-in-progress: true

env:
    BUILD_DIR: build
    BUILD_TYPE: Release
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    SCCACHE_GHA_ENABLED: true
    VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

permissions:
    contents: read
    packages: write

jobs:
    changed:
        name: check-changed
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{steps.changed-files.outputs.only_changed == 'true'}}

        steps:
            - name: Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  fetch-depth: 2

            - name: Get changed files
              id: changed-files
              run: |
                  CURRENT_COMMIT=$(git rev-parse HEAD)
                  PREVIOUS_COMMIT=$(git rev-parse HEAD^)
                  CHANGED_FILES=$(git diff --name-only "$PREVIOUS_COMMIT" "$CURRENT_COMMIT")

                  only_changed=false

                  if [ -n "$CHANGED_FILES" ]; then
                    echo "Changed files:"
                    echo "$CHANGED_FILES"

                    FILTERED_FILES=$(echo "$CHANGED_FILES" | grep "^\.github/workflows/build\.yml$" || echo "$CHANGED_FILES" | grep -vE "^(docs|\.github|.*\.md)" || true)
                    if [ ! -n "$FILTERED_FILES" ]; then
                      echo "Found only documentation changes"
                      only_changed=true
                    fi
                  else
                    echo "No changes found"
                    only_changed=true
                  fi

                  echo "only_changed=$only_changed" >> $GITHUB_OUTPUT

    lint:
        needs: changed
        if: needs.changed.outputs.should_skip != 'true'
        runs-on: ubuntu-latest

        timeout-minutes: 30

        steps:
            - name: Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Set up python
              uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
              with:
                  python-version: '3.13'

            - name: Run pre-commit
              uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
              with:
                  extra_args: cpplint --all-files

    build:
        needs: changed
        if: needs.changed.outputs.should_skip != 'true'
        name: ${{matrix.name}}
        runs-on: ${{matrix.os}}

        timeout-minutes: 30

        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: mac
                      os: macos-latest
                      preset: ci-osx-release

                    - name: windows
                      os: windows-latest
                      preset: ci-windows-release

                    - name: linux
                      os: ubuntu-latest
                      preset: ci-linux-release

        steps:
            - name: Checkout code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Extract git commit id from vcpkg configuration
              id: vcpkg-commit-id
              shell: bash
              run: |
                  id=$(jq -r '."builtin-baseline"' vcpkg.json)
                  echo "id=$id" >> $GITHUB_OUTPUT
                  echo "VCPKG_GIT_COMMIT_ID=$id" >> $GITHUB_ENV

            - name: Install linux packages
              if: runner.os == 'Linux'
              run: >
                  sudo apt-get update -qq &&
                  sudo apt-get install -qq -y --no-install-recommends libtool libasound2-dev libgl1-mesa-dev libltdl-dev
                  libx11-dev libxcursor-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxrandr-dev
                  mono-complete

            - name: Install mono
              if: runner.os == 'macOS'
              run: brew install mono

            - name: Setup MSVC toolchain
              if: runner.os == 'Windows'
              uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0

            - name: Setup CMake
              uses: lukka/get-cmake@f5b8fbb4d77cec1acc5a5f9f0df4beffaf5d98d9 # v4.3.4

            - name: Configure sccache
              shell: bash
              run: |
                  echo "ACTIONS_RESULTS_URL=${ACTIONS_RESULTS_URL}" >> $GITHUB_ENV
                  echo "ACTIONS_RUNTIME_TOKEN=${ACTIONS_RUNTIME_TOKEN}" >> $GITHUB_ENV

            - name: Cache the build
              uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@305c06bd4dee21e23dcf142c85c657a993f7aa1a # v11
              with:
                  vcpkgGitURL: 'https://github.com/microsoft/vcpkg.git'

            - name: Cache vcpkg downloads
              if: runner.os == 'Windows'
              uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
              with:
                  path: ${{env.VCPKG_ROOT}}/downloads
                  key: vcpkg-downloads-windows-${{steps.vcpkg-commit-id.outputs.id}}
                  restore-keys: vcpkg-downloads-windows-

            - name: Setup vcpkg NuGet credentials
              shell: bash
              run: |
                  [[ "$RUNNER_OS" != "Windows" ]] && unset VCPKG_FORCE_SYSTEM_BINARIES
                  NUGET=$(vcpkg fetch nuget | tail -n 1)
                  [[ "$NUGET" == *.exe && "$RUNNER_OS" != "Windows" ]] && NUGET="mono $NUGET"
                  $NUGET sources add \
                    -Name "GitHub" \
                    -Source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json" \
                    -UserName "${{github.actor}}" \
                    -Password "${{secrets.GITHUB_TOKEN}}" \
                    -StorePasswordInClearText
                  $NUGET setapikey "${{secrets.GITHUB_TOKEN}}" \
                    -Source "https://nuget.pkg.github.com/${{github.repository_owner}}/index.json"

            - name: Create build tree
              shell: bash
              run: |
                  [[ "$RUNNER_OS" != "Windows" ]] && unset VCPKG_FORCE_SYSTEM_BINARIES
                  cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} --preset ${{matrix.preset}}

            - name: Build
              run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target install game --parallel 4

            - name: Upload artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
              with:
                  name: maze-${{matrix.name}}
                  path: ${{github.workspace}}/out/install/${{matrix.preset}}/
                  overwrite: true
                  retention-days: 1
                  if-no-files-found: error
